---
- name: Install containerd
  include_tasks: "{{ ansible_pkg_mgr | lower }}_install_containerd.yaml"

- name: Set containerd service to the desired state
  become: yes
  ansible.builtin.service:
    name: containerd
    state: "{{ service_containerd_state }}"
    enabled: "{{ service_containerd_enabled }}"

- name: Configure containerd
  include_tasks: configure_containerd.yaml
  when: containerd_config_edit | bool == true

# Execute handlers right after this
- ansible.builtin.meta: flush_handlers