logger:
  file:
    path: /var/log/open5gs/udm.log

global:

udm:
  sbi:
    server:
      - dev: eth0
        port: {{ .Values.global.containerPorts.sbi }}
    client:
      nrf:
        {{- if eq .Release.Name "nrf" }}
        - uri: http://nrf-service-sbi:{{ .Values.global.containerPorts.sbi }}
        {{- else }}
        - uri: http://{{ .Release.Name }}-nrf-service-sbi:{{ .Values.global.containerPorts.sbi }}
        {{- end }}
