apiVersion: v1
kind: ConfigMap
metadata:
  name: udm-configmap
data:
  udm.yaml: |
    logger:
      file: /open5gs/install/var/log/open5gs/udm.log

    global:
      max:
        ue: 1024

    udm:
      sbi:
        server:
          - dev: eth0
            port: 80
        client:
          nrf:
            - uri: http://nrf-service-sbi.default.svc.cluster.local:80
