---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-deployment
  namespace: {{ include "common.names.namespace" . }}
  labels:
    nf: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: nrf
  template:
    metadata:
      labels:
        nf: nrf
    spec:
      containers:
      - name: {{ include "common.names.fullname" . }}
        image: {{ template "nrf.image" . }}
        args: ["-c", "/open5gs/config/nrf.yaml"]
        ports:
        - name: sbi
          containerPort: {{ .Values.global.containerPorts.sbi }}
        volumeMounts:
        - name: nrf-volume-config
          mountPath: /open5gs/config/nrf.yaml
          subPath: nrf.yaml
      volumes:
      - name: nrf-volume-config
        configMap:
          name: {{ include "common.names.fullname" . }}-configmap
