---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-deployment
  namespace: {{ include "common.names.namespace" . }}
  labels:
    nf: nssf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: nssf
  template:
    metadata:
      labels:
        nf: nssf
    spec:
      containers:
      - name: {{ include "common.names.fullname" . }}
        image: {{ template "nssf.image" . }}
        args: ["-c", "/open5gs/config/nssf.yaml"]
        ports:
        - name: sbi
          containerPort: {{ .Values.global.containerPorts.sbi }}
        volumeMounts:
        - name: nssf-volume-config
          mountPath: /open5gs/config/nssf.yaml
          subPath: nssf.yaml
      volumes:
      - name: nssf-volume-config
        configMap:
          name: {{ include "common.names.fullname" . }}-configmap
