apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-configmap
data:
  pcf.yaml: |
    db_uri: mongodb://db-service.default.svc.cluster.local/open5gs

    logger:
      file:
        path: /open5gs/install/var/log/open5gs/pcf.log

    global:

    pcf:
      sbi:
        server:
          - dev: eth0
            port: 80
        client:
          nrf:
            - uri: http://nrf-service-sbi.default.svc.cluster.local:80
