---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-service-sbi
  namespace: {{ include "common.names.namespace" . }}
spec:
  selector:
    nf: pcf
  ports:
    - name: sbi
      port: {{ .Values.global.containerPorts.sbi }}
      targetPort: {{ .Values.global.containerPorts.sbi }}
  type: ClusterIP
