apiVersion: apps/v1
kind: Deployment
metadata:
  name: udr-deployment
  labels:
    nf: udr
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: udr
  template:
    metadata:
      labels:
        nf: udr
    spec:
      containers:
      - name: udr
        image: borieher/udr:v2.7.0
        args: ["-c", "/open5gs/config/udr.yaml"]
        ports:
        - name: sbi
          containerPort: 80
        volumeMounts:
        - name: udr-volume-config
          mountPath: /open5gs/config/udr.yaml
          subPath: udr.yaml
      volumes:
      - name: udr-volume-config
        configMap:
          name: udr-configmap
