---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-service-gtpu
  namespace: {{ include "common.names.namespace" . }}
  annotations:
    {{- if eq .Values.services.gtpu.provider "MetalLB" }}
    metallb.universe.tf/loadBalancerIPs: {{ .Values.services.gtpu.loadBalancerIP }}
    {{- end }}
spec:
  selector:
    nf: upf
  ports:
    - name: gtpu
      port: 2152
      targetPort: 2152
      protocol: UDP
  type: {{ .Values.services.gtpu.type }}
