apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-configmap
data:
  nrf.yaml: |
    logger:
      file:
        path: /open5gs/install/var/log/open5gs/nrf.log

    global:

    nrf:
      sbi:
        server:
          - dev: eth0
            port: 80
