apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-configmap
data:
  nrf.yaml: |
    logger:
      file: /open5gs/install/var/log/open5gs/nrf.log

    global:
      max:
        ue: 1024

    nrf:
      sbi:
        server:
          - dev: eth0
            port: 80
