apiVersion: apps/v1
kind: Deployment
metadata:
  name: nrf-deployment
  labels:
    nf: nrf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: nrf
  template:
    metadata:
      labels:
        nf: nrf
    spec:
      containers:
      - name: nrf
        image: borieher/nrf:v2.7.1
        args: ["-c", "/open5gs/config/nrf.yaml"]
        ports:
        - name: sbi
          containerPort: 80
        volumeMounts:
        - name: nrf-volume-config
          mountPath: /open5gs/config/nrf.yaml
          subPath: nrf.yaml
      volumes:
      - name: nrf-volume-config
        configMap:
          name: nrf-configmap
