---
- name: Get kubeproxy's configuration
  ansible.builtin.command: "kubectl get configmap kube-proxy -n kube-system -o yaml"
  register: kubeproxy_config

- name: Copy kubeproxy's configuration to /tmp/kubeproxy_config.yaml
  become: yes
  ansible.builtin.copy:
    dest: /tmp/kubeproxy_config.yaml
    content: "{{ kubeproxy_config.stdout }}"

# TODO (borieher): Execute when kubernetes_version > v1.14 and kubeproxy_mode == ipvs
- name: Enable strict ARP mode
  become: yes
  ansible.builtin.replace:
    path: /tmp/kubeproxy_config.yaml
    regexp: 'strictARP: false'
    replace: 'strictARP: true'

- name: Apply kubeproxy's modified configuration
  ansible.builtin.command: "kubectl apply -f /tmp/kubeproxy_config.yaml -n kube-system"

- name: Install MetalLB
  ansible.builtin.command: "kubectl apply -f {{ metallb_manifest_url }}"
  register: metallb_result
  changed_when: "'created' in metallb_result.stdout or 'already exists' in metallb_result.stdout"
  until: metallb_result is not failed
  retries: 10
  delay: 5

- name: Apply MetalLB configuration values to layer 2 advertisement mode template
  ansible.builtin.template:
    src: l2advertisement.j2
    dest: "{{ metallb_advertisement_config_file_path }}"
  when: metallb_advertisement_mode == "l2"

# TODO (borieher): Implement BGP advertisement mode template

- name: Apply MetalLB configuration values to IP address pool template
  ansible.builtin.template:
    src: ipaddresspool.j2
    dest: "{{ metallb_ipaddresspool_config_file_path }}"

- name: Configure MetalLB advertisement mode
  ansible.builtin.command: "kubectl apply -f {{ metallb_advertisement_config_file_path }}"
  register: metallb_advertisement_result
  changed_when: "'created' in metallb_advertisement_result.stdout or 'already exists' in metallb_advertisement_result.stdout"
  until: metallb_advertisement_result is not failed
  retries: 15
  delay: 20

- name: Configure MetalLB IP address pool
  ansible.builtin.command: "kubectl apply -f {{ metallb_ipaddresspool_config_file_path }}"
  register: metallb_ipaddresspool_result
  changed_when: "'created' in metallb_ipaddresspool_result.stdout or 'already exists' in metallb_ipaddresspool_result.stdout"
  until: metallb_ipaddresspool_result is not failed
  retries: 15
  delay: 20
