apiVersion: apps/v1
kind: Deployment
metadata:
  name: bsf-deployment
  labels:
    nf: bsf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: bsf
  template:
    metadata:
      labels:
        nf: bsf
    spec:
      containers:
      - name: bsf
        image: borieher/bsf:v2.7.0
        args: ["-c", "/open5gs/config/bsf.yaml"]
        ports:
        - name: sbi
          containerPort: 80
        volumeMounts:
        - name: bsf-config-volume
          mountPath: /open5gs/config/bsf.yaml
          subPath: bsf.yaml
      volumes:
      - name: bsf-config-volume
        configMap:
          name: bsf-configmap
