apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-configmap
data:
  nssf.yaml: |
    logger:
      file:
        path: /open5gs/install/var/log/open5gs/nssf.log

    global:

    nssf:
      sbi:
        server:
          - dev: eth0
            port: 80
        client:
          nrf:
            - uri: http://nrf-service-sbi.default.svc.cluster.local:80
          nsi:
            - uri: http://nrf-service-sbi.default.svc.cluster.local:80
              s_nssai:
                sst: 1
                sd: 000001
