logger:
  file:
    path: /open5gs/install/var/log/open5gs/amf.log

global:

amf:
  sbi:
    server:
      - dev: eth0
        port: {{ .Values.global.containerPorts.sbi }}
    client:
      nrf:
        {{- if eq .Release.Name "nrf" }}
        - uri: http://nrf-service-sbi:{{ .Values.global.containerPorts.sbi }}
        {{- else }}
        - uri: http://{{ .Release.Name }}-nrf-service-sbi:{{ .Values.global.containerPorts.sbi }}
        {{- end }}
  ngap:
    server:
      - dev: eth0
  guami:
    - plmn_id:
        mcc: {{ .Values.global.mobileNetwork.plmn.mcc }}
        mnc: {{ .Values.global.mobileNetwork.plmn.mnc }}
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: {{ .Values.global.mobileNetwork.plmn.mcc }}
        mnc: {{ .Values.global.mobileNetwork.plmn.mnc }}
      tac: {{ .Values.global.mobileNetwork.plmn.tac }}
  plmn_support:
    - plmn_id:
        mcc: {{ .Values.global.mobileNetwork.plmn.mcc }}
        mnc: {{ .Values.global.mobileNetwork.plmn.mnc }}
      s_nssai:
        - sst: {{ .Values.global.mobileNetwork.plmn.s_nssai.sst }}
          sd: {{ .Values.global.mobileNetwork.plmn.s_nssai.sd }}
  security:
      integrity_order : [ NIA2, NIA1, NIA0 ]
      ciphering_order : [ NEA0, NEA1, NEA2 ]
  network_name:
    full: {{ .Values.global.mobileNetwork.name }}
  amf_name: open5gs-{{ include "common.names.fullname" . }}
  time:
    t3512:
      value: 540
