---
# kubernetes specific variables
kubernetes_role: control_plane
kubernetes_schedule_pods_on_control_plane: true

# kubernetes pod network add-on variables
kubernetes_pod_network_add_on: calico
kubernetes_pod_network_add_on_version: v3.27.0
kubernetes_pod_network_cidr: 10.13.0.0/24

# calico pod network add-on specific variables
calico_tigera_operator_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ kubernetes_pod_network_add_on_version }}/manifests/tigera-operator.yaml"
calico_custom_resources_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/{{ kubernetes_pod_network_add_on_version }}/manifests/custom-resources.yaml"

## kubernetes prerequisites options
kubernetes_prerequisites_kernel_modules:
  - overlay
  - br_netfilter

# Package manager specific variables

## apt
apt_keyrings_dir: /etc/apt/keyrings
apt_kubernetes_release_channel: stable
apt_kubernetes_version: v1.29
