apiVersion: v1
kind: ConfigMap
metadata:
  name: upf-configmap
data:
  upf.yaml: |
    logger:
      file:
        path: /open5gs/install/var/log/open5gs/upf.log

    global:

    upf:
      pfcp:
        server:
          - dev: eth0
        client:
      gtpu:
        server:
          - dev: eth0
            advertise: 10.33.0.3
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
