apiVersion: v1
kind: Service
metadata:
  name: upf-service-gtpu
spec:
  selector:
    nf: upf
  ports:
    - name: gtpu
      port: 2152
      targetPort: 2152
      protocol: UDP
  type: LoadBalancer
