apiVersion: v1
kind: Service
metadata:
  name: upf-service-gtpu
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.33.0.3
spec:
  selector:
    nf: upf
  ports:
    - name: gtpu
      port: 2152
      targetPort: 2152
      protocol: UDP
  type: LoadBalancer
