---
- name: Set up prerequisites for kubernetes
  include_tasks: prerequisites_kubernetes.yaml

- name: Install kubelet, kubeadm and kubectl
  include_tasks: "{{ ansible_pkg_mgr | lower }}_install_kubernetes.yaml"

- name: Ensure kubelet service is started and enabled
  become: yes
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true

- name: Setup kubernetes
  include_tasks: setup_kubernetes.yaml

- name: Setup Calico as Pod network add-on
  include_tasks: setup_calico.yaml
  when: kubernetes_role == "control_plane" and kubernetes_pod_network_add_on == "calico"

# TODO (borieher): Find a fancier way to handle the error output
- name: Schedule Pods on control plane
  ansible.builtin.command: "kubectl taint nodes --all node-role.kubernetes.io/control-plane-"
  when: kubernetes_role == "control_plane" and (kubernetes_schedule_pods_on_control_plane | bool == true)
  failed_when: false
  ignore_errors: yes

- name: Set roles on nodes
  ansible.builtin.command: "kubectl label node {{ hostvars[item].ansible_host }} node-role.kubernetes.io/node="
  with_items: "{{ groups['nodes'] }}"
  when: kubernetes_role == "control_plane"
