---
- name: Gather services
  ansible.builtin.service_facts:

- name: Disable firewalld for Calico
  become: yes
  ansible.builtin.service:
    name: firewalld
    state: stopped
    enabled: false
  when: "'firewalld' in services"

- name: Install Calico Tigera Operator
  ansible.builtin.command: "kubectl create -f {{ calico_tigera_operator_manifest_url }}"
  register: tigera_operator_result
  changed_when: "'created' in tigera_operator_result.stdout or 'already exists' in tigera_operator_result.stdout"
  until: tigera_operator_result is not failed
  retries: 10
  delay: 5

- name: Download Calico custom resources
  become: yes
  ansible.builtin.get_url:
    url: "{{ calico_custom_resources_manifest_url }}"
    dest: "/tmp/calico_{{ kubernetes_pod_network_add_on_version }}_custom_resources.yaml"

- name: Modify Calico CIDR
  become: yes
  ansible.builtin.replace:
    path: "/tmp/calico_{{ kubernetes_pod_network_add_on_version }}_custom_resources.yaml"
    regexp: '(\t*cidr:) 192.168.0.0/16$'
    replace: '\1 {{ kubernetes_pod_network_cidr }}'

- name: Install Calico custom resources
  ansible.builtin.command: "kubectl create -f /tmp/calico_{{ kubernetes_pod_network_add_on_version }}_custom_resources.yaml"
  register: custom_resources_result
  changed_when: "'created' in custom_resources_result.stdout or 'already exists' in custom_resources_result.stdout"
  until: custom_resources_result is not failed
  retries: 10
  delay: 5
