apiVersion: v1
kind: Service
metadata:
  name: webui-service
spec:
  selector:
    app: webui
  ports:
    - name: webui
      port: 9999
      targetPort: 9999
      nodePort: 30999
  type: NodePort
