---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}-configmap
  namespace: {{ include "common.names.namespace" . }}
data:
  ausf.yaml: |
    {{ template "ausf.config" . }}
