---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-service
  namespace: {{ include "common.names.namespace" . }}
spec:
  selector:
    app: webui
  ports:
    - name: webui
      port: {{ .Values.global.containerPorts.webui }}
      targetPort: {{ .Values.global.containerPorts.webui }}
  {{- if eq .Values.services.webui.type "NodePort" }}
      nodePort: {{ .Values.services.webui.nodePort }}
  type: NodePort
  {{- else if eq .Values.services.webui.type "ClusterIP" }}
  type: ClusterIP
  {{- end }}