---
- hosts: localhost
  gather_facts: False
  vars_files:
    - ../vars/aws.yaml
  module_defaults:
    group/aws:
      aws_access_key: "{{ aws_access_key }}"
      aws_secret_key: "{{ aws_secret_key }}"
      region: "eu-north-1"

  tasks:
    - name: "Provision the EC2 instances for the k8s cluster"
      amazon.aws.ec2_instance:
        name: "{{ item }}"
        state: running
        key_name: "Borjis-AWS"
        instance_type: t3.micro
        security_group: sg-0a5a9fb43ef7fd5fd
        network:
          assign_public_ip: true
          delete_on_termination: true
        volumes:
          - device_name: /dev/xvda
            ebs:
              volume_size: 10
        image_id: ami-0b27735385ddf20e8
      register: result
      with_items:
        - aws-k8s-master
        - aws-k8s-node-1
        - aws-k8s-node-2
