apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-configmap
data:
  ausf.yaml: |
    logger:
      file: /open5gs/install/var/log/open5gs/ausf.log

    global:
      max:
        ue: 1024

    ausf:
      sbi:
        server:
          - dev: eth0
            port: 80
        client:
          nrf:
            - uri: http://nrf-service-sbi.default.svc.cluster.local:80
