apiVersion: apps/v1
kind: Deployment
metadata:
  name: ausf-deployment
  labels:
    nf: ausf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: ausf
  template:
    metadata:
      labels:
        nf: ausf
    spec:
      containers:
      - name: ausf
        image: borieher/ausf:v2.7.1
        args: ["-c", "/open5gs/config/ausf.yaml"]
        ports:
        - name: sbi
          containerPort: 80
        volumeMounts:
        - name: ausf-volume-config
          mountPath: /open5gs/config/ausf.yaml
          subPath: ausf.yaml
      volumes:
      - name: ausf-volume-config
        configMap:
          name: ausf-configmap
