apiVersion: v1
kind: Service
metadata:
  name: amf-service-ngap
spec:
  selector:
    nf: amf
  ports:
    - name: ngap
      port: 38412
      targetPort: 38412
      protocol: SCTP
  type: LoadBalancer
