apiVersion: v1
kind: Service
metadata:
  name: amf-service-ngap
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.33.0.2
spec:
  selector:
    nf: amf
  ports:
    - name: ngap
      port: 38412
      targetPort: 38412
      protocol: SCTP
  type: LoadBalancer
