apiVersion: apps/v1
kind: Deployment
metadata:
  name: smf-deployment
  labels:
    nf: smf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf: smf
  template:
    metadata:
      labels:
        nf: smf
    spec:
      containers:
      - name: smf
        image: borieher/smf:v2.7.1
        args: ["-c", "/open5gs/config/smf.yaml"]
        ports:
        - name: sbi
          containerPort: 80
        - name: pfcp
          containerPort: 8805
          protocol: UDP
        volumeMounts:
        - name: smf-volume-config
          mountPath: /open5gs/config/smf.yaml
          subPath: smf.yaml
      volumes:
      - name: smf-volume-config
        configMap:
          name: smf-configmap
