---
# service manager options
service_containerd_state: started
service_containerd_enabled: true

# Package manager specific variables

## apt
apt_keyrings_dir: /etc/apt/keyrings
# Note: the - removes the whitespaces from the block (arm64)
apt_docker_arch: "{% if ansible_architecture == 'aarch64' -%} arm64 {% endif %}"
apt_docker_release_channel: stable

## TODO (borieher): yum

# containerd configuration options
containerd_config_edit: true
containerd_config_cgroup_driver: systemd
